### ISSUE TITLE
Insert PID type in template dataset publication tables

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#115]
**Description**
Affects science europe table 5a (Data publication and access conditions) and equivalent IV.2 in FWF template.
Insert in the PID column the PID type information  ("PID Systems") extracted from r3data.

**Proposed solution**
Perceive the PID type from r3data.

**Alternative solution**
If not available in r3data then allow implementing institutions to have a list of repositories that will provide a hardcoded information.
e.g. TUWRD would dictate PID type "DOI"

**Additional context**
Currently the field is empty, and researchers do not know what input is required.

_If this issue requests multiple changes consider using checkboxes or lists._

**Comment by ChristianeStork** [comment]
This is closely related to "Add PID information to the repository table...".
