### ISSUE TITLE
Export: Prefill Version Table

### ISSUE THREAD

**Issue by rekt-hard** [tuwien-csd/damap-backend#130]
When exporting a document, the version table list is not prefilled.
Available DMP versions can be inserted into the table to reduce manual work and possible user errors.

Additionally, the license of the DMP is set automatically. This might not be desired.

![image](https://github.com/tuwien-csd/damap-backend/assets/72449192/bc4031db-2710-4b14-b930-647af4fe470a)

**Comment by ValentinFutterer** [comment]
Input from Christiane on how the section should look like:
Science Europe:

![SE](https://github.com/tuwien-csd/damap-backend/assets/80054001/c49283bd-6709-42b5-a20c-b57703903b66)


FWF:

![FWF](https://github.com/tuwien-csd/damap-backend/assets/80054001/d4a34405-c2a9-4e98-8c36-2b973e9b6431)

Horizon Europe:

![HE](https://github.com/tuwien-csd/damap-backend/assets/80054001/fca1c494-f017-42fd-afe3-8da63b39520a)
