### ISSUE TITLE
keycloak: jboss/keycloak on dockerhub not available

### ISSUE THREAD

**Issue by larnhold** [tuwien-csd/damap-backend#173]
**Describe the bug**
When running Docker Compose for the project, the following issues in the attached screenshot are encountered and the containers do not start.

**Is this a regression?**
Yes

**Steps to Reproduce**
docker compose up

**Expected behavior**
Docker compose should not fail

**Screenshots**
The screenshot shows the error messages that appear when running the docker-compose.  It fails when pulling keycloak from dockerhub.

![Screenshot 2024-03-21 113643](https://github.com/tuwien-csd/damap-backend/assets/10672708/b58dde1a-7dcb-4d45-8378-f8f57ce70e8d)

**Environment**
 - Damap version 3.0.0

**Additional context**
Freshly checkout DAMAP backend

**Comment by rekt-hard** [comment]
Still have to review the PR and merge it. If you can do that, we can close the issue :)
