### ISSUE TITLE
Email disappears for contributor if they have ORCID ID

### ISSUE THREAD

**Issue by ValentinFutterer** [tuwien-csd/damap-backend#178]
**This is a copy of https://github.com/tuwien-csd/damap-frontend/issues/190 , since the issue is backend related.**

Describe the bug
When adding a project contributor who has an ORCID ID and an email address, the email address disappears. This happens both in DAMAP and the TU Wien DMP Tool

Is this a regression?
No.

To Reproduce

Go to 'People involved in data management'
Search for a person from the TU Wien address book that has an ORCID ID and email address, e.g. Tomasz or Christiane. OR manually add a person with and email address and ORCID ID
Click "Save changes"
See email disapear
Expected behavior
All info input stays in tool, including email address

Environment

Browser Edge version 122
Damap and TU Wien DMP Tool
Additional context

**Comment by DerekMolnar** [comment]
Needs to be fixed in the TU Wien DMP Tool

**Comment by ZenoLC** [comment]
This repository is for the damap open source project only, please send requests for the institutional deployment internally
