### ISSUE TITLE
Check if DAMAP follows the RDA DMP Common Standard for machine-actionable Data Management Plans when exporting to json

### ISSUE THREAD

**Issue by ValentinFutterer** [tuwien-csd/damap-backend#186]
It is unclear if the standard is followed correctly. Compare with https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard?tab=readme-ov-file to find out and fix it if necessary.

**Comment by DerekMolnar** [comment]
To follow the standard, DAMAP would need to assign a DMP with a PID. If a PID is added to the DMP by the user, then the DMP would meet the standard.  However, the maDMP requirements will change as part of the OSTrails project.

**Comment by rekt-hard** [comment]
@DerekMolnar  can we close this issue?

**Comment by DerekMolnar** [comment]
@rekt-hard yes
