### ISSUE TITLE
Export: Contributors are not listed

### ISSUE THREAD

**Issue by rekt-hard** [tuwien-csd/damap-backend#231]
**Describe the bug**
The contributors are not listed in the exported document.
FWF and Horizon Europe documents do not list the contributors. Science Europe has a section of the contributors.

**Is this a regression?**
No.

**Steps to Reproduce**
1. Create a DMP
2. Add some contributors
3. Export document (FWF or Horizon Europe)
4. Open document
5. Contributors are not listed anywhere in the document.

**Expected behavior**
Contributors should be listed in the document in a table (similar to Science Europe template).

**Screenshots**
Science Europe:
![image](https://github.com/user-attachments/assets/e443bb07-a8f3-4569-b5bf-3abda55fb9be)

**Additional context**

**Comment by ValentinFutterer** [comment]
@ChristianeStork what is your opinion on this?

**Comment by DerekMolnar** [comment]
Thanks for taking this on @ValentinFutterer @rekt-hard.  Before her vacation, I discussed this with @ChristianeStork as an example of DAMAP user text missing when exported. I would proceed with the change, unless you have specific concerns.  If so, please elaborate.  Thanks!
