### ISSUE TITLE
Live DMP Export Preview

### ISSUE THREAD

**Issue by GeoffreyKarnbach** [tuwien-csd/damap-backend#259]
**Description**

When working on a DMP (either during development to try out template changes, or as a user), to check out the current export state, a Word Document has to be exported everytime.

In order to enhance productivity, a Live Preview of the DMP Export would be very useful.

**Proposed solution**

There are two approaches, that may both be explored for displaying the preview in the Frontend: 
- A split screen view (such as in overleaf) 
![image](https://github.com/user-attachments/assets/80723611-353d-4715-9508-d23f042f0c3b)
- An overlay approach (triggered through a button press to open a popup with the preview) 
![image](https://github.com/user-attachments/assets/ad31aa21-03f5-47ae-b3f9-fda42899dff0)

Both approaches have advantages and disadvantages:
- The split screen view enables the user to always see the state of the preview (updated for instance when saving the DMP after making changes), but the usability on small screens might be impacted.
- The overlay allows better usability on smaller screens (especially for laptops) but the user has to press an additional button to be able to preview the current state.

In addition to the location in the frontend, different technical challenges regarding the rendering and backend exist:
- In the frontend, a DOCX to HTML renderer can be used to display (https://github.com/VolodymyrBaydalka/docxjs), no data has to be exposed to any third party services and the file can be kept private (behind an authentication wall), as it will only be used by an authenticated user within the frontend. Main issue with that approach is, that the rendering is not perfect and has some small flaws
![image](https://github.com/user-attachments/assets/5b43bd21-3da5-4c2e-8d6a-15fff61c0e20)
- Alternatively, a live preview iframe vom Microsoft can be used. This renders the Document in a perfect manner, but leads to a public (see the next paragraph) available word document and it exposes it to Microsoft Services. Furthermore, this option is only available in a deployed environment, where the backend has a static URL (not localhost) that can be resolved my Microsoft services.
![image](https://github.com/user-attachments/assets/ac3b07e1-90c1-4b7f-805f-d416c1194c72)

The approach to offer in localhost and in a deployed environment the live preview feature would be:
- Use the JS library to render the DOCX to HTML in the dev environment (not perfect, but probably good enough to check for quick updates made in the DMP Form)
- Use the Microsoft IFrame in deployment, ensuring a reliable rendering (and possible as the backend is hosted).

As mentioned before, the files need to be "publicly" available for the Microsoft Iframe to be able to access them. As the IFrame may also take API requests as input (as long as a Word Document is returned), following approach would lead to better security:
- Persist the generated preview Word Documents on the Server with a UUID as name (32 characters for instance)
- Add a OTP / Password (64 characters) that is passed as query param to the Backend call.
- Ensure that not used export files are deleted as soon as possible (keep track of the current filename in a DB entity, remove the file before generating a new export file for a given project).

Through this approach, the "public" files, are protected by a 32 characters UUID name (that would have to be guessed) and a 64 characters password within a "short" timeframe, making it effectively not feasible for an attacker (same would apply to any other endpoint if a JWT is leaked, the password has to be treated as an authentication/access token).

This approach would furthermore allow users to generate exported documents, that can be shared using an URL and the password as query param to any non authenticated user.

An approach to persisting those temporary files would be to the "temp" environment of the operating system (%TEMP% for windows, /var/tmp or /tmp for Unix).

**Alternative solution**
Generate a PDF on Server Side from the Word Document (no feasible approach was found, possible with libraries, but requires Microsoft Word to be installed in the Server Environment => not easily possible in Linux). This approach would make the entire approach easier, as rendering a PDF in the Frontend is trivial.

**Comment by rekt-hard** [comment]
Possible solution for converting the document to PDF:
- Gotenberg:
  - https://github.com/gotenberg/gotenberg
  - Could provide it as a default service in docker-compose and convert via their API. Might come in handy later as well.
- docx4j
  - https://github.com/plutext/docx4j
  - Java library for conversion

**Comment by GeoffreyKarnbach** [comment]
Current prototype implementation in those branches:

https://github.com/tuwien-csd/damap-backend/tree/gk/252-preselection-of-the-template-real-time-view
https://github.com/tuwien-csd/damap-frontend/tree/gk/252-preselection-of-the-template-real-time-view
