### ISSUE TITLE
Enable adding contributors sourced from ORCID.

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#44]
In the frontend the user should be able, like with the search field for their person database, to search for researchers in the ORCID database by using name or ORCID-ID.
this request should be managed by the backend, which will use the institutions ORCID credentials to make the request with ORCID, and then map it to our ContributorDO objects for the frontend to consume.

**Comment by rekt-hard** [comment]
The person resource and its `/search` shall be used and adapted. A query parameter (`searchService`) defines which search service should be queried.

Following implementation possibilities have been defined:
- Several PersonService definitions via config
  - Define which services are available in the config
  - Provide config per service as well
  - Read complete PersonService config in resource for dynamic functionality
- Extend resource with ORCID PersonService only
  - Hardcode ORCID service into resource
  - Define ORCID config variables
    - If set, allow search via ORCID API

Either case should adapt the config for the frontend, such that it knows which services are available. This allows the frontend to adapt to the config and display different options. This approach may also be used for other resources - such as project search.

After offline discussion, we settled for a first implementation to only include the ORCID search service and add configuration values for it.
