### ISSUE TITLE
force docker compose to download new image

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#58]

**Comment by DerekMolnar** [comment]
@ValentinFutterer and I spoke to @SotosTsepe  about this today.  Sotiris believes this is relatively easy to do and can help.  It is not an urgent task, so I have tentatively assigned Q1 24 for it to be completed.

**Comment by rekt-hard** [comment]
Could be a starting point: https://docs.docker.com/compose/compose-file/05-services/#pull_policy

**Comment by SotosTsepe** [comment]
I think this should do the trick: `docker compose down && docker compose build --pull && docker compose up -d`.

**Comment by rekt-hard** [comment]
AFAIK, the idea was to take the burden away from the user and have `docker-compose` pull the images implicitly (via the `docker-compose file`). Executing `docker compose up`, should pull the latest images, if possible.
If it is not possible in that way, manual pulling is always an option (as you mentioned). Then we can document this and it is up to the user which commands they use.
