### ISSUE TITLE
Allow internal storages to be disabled for the frontend

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#95]
**Description**
Currently the design of the application does not allow to retire internal storage options from the available list of options.
Simply deleting them will result in a foreign key conflict.
So we must be able to remove them in a way that would allow continued support for old DMPs that have these options selected, while removing it from the list of selectable options available in the frontend.

**Proposed solution**
Possibly add a column (e.g. "active") to the database, to indicate if a storage option is deprecated.
The frontend needs to hide this option if tagged as inactive.
We still need to communicate this option to the frontend, in order for it to display it if it was selected in a past DMP.
The backend validator needs to alert, in case the user attempts to indicate an inactive storage option in their request.

**Alternative solution**
The above solution is from the top of my head, please feel free to use different approaches.

**Additional context**
Internal storage options are added by implementing institutions in their custom implementation. They should have a possibility of changing these options after the fact.

**Comment by GeoffreyKarnbach** [comment]
Currently the changes have been implemented, we still need to take a look at the Backend Validator, there is a bug (possibly related to the Management of Panache Entities) that needs to be adressed (the code is commented out for now). 

The remaining feature works perfectly fine.
